# This will appear before many messages from the plugin.
message-prefix: '&5[&dWbsShulkers&5]'

# Use a minecraft colour code here to pick the message colour
message-colour: 'd'

# The highlight colour (to complement the above colour)
highlight-colour: 'b'

# Errors will be this colour.
error-colour: 'c'

# Error highlights
error-highlight: '7'

settings:
  # This appears before lore lines associated with options, and supports "&" colours.
  lore-format: '&7'